# Utilisez une image Docker avec Maven
# Utilisez la même image pour tous les jobs
image: maven:3-eclipse-temurin-17-alpine

cache:
  key: "$CI_SSH_NAME"
  path:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

deploy:
  only:
    - master
  before_script:
    - chmod 777 ./ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
    - apk add openssh-client
  script:
    - cd tp4
    - mvn clean package
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY target/todos.war gitlabci@192.168.75.87:/opt/tomcat/webapps/v3.war

